### ISSUE TITLE
Error when creating portals in different worlds

### ISSUE THREAD

**Issue by BronzWarq** [mehboss/TranspositionRitual#6]
### What happened?

I make portals in different worlds

### What was supposed to happen?

When I make portals in different worlds, the server gives an error

### How do I reproduce this issue?

```bash
1.To repeat this error you need to make a portal in one world and another portal in another world
```

### Relevant log output

```shell
https://paste.helpch.at/ufilowocin.rb
```

### Server Version

SSSpigot 1.20.2

### Plugin Version

1.4-BETA

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of TP Rituals and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello, thank you for your patience while I was MIA. Please download the newest update [here](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-teleportation-rituals-1-8-x-1-20-x-creation-limit-networking-system-%E2%97%84%E2%97%84.110584/update?update=564059), and your issue will be resolved.
