### ISSUE TITLE
Color codes for sent messages not working

### ISSUE THREAD

**Issue by omgitsKit** [mehboss/TranspositionRitual#8]
### What happened?

Some messages sent by the plugin like "Teleporting in 6.. please wait" aren't getting the colors properly
![image](https://github.com/mehboss/TranspositionRitual/assets/116936416/6cd40e64-112f-43ff-b396-b5b908fc3383)

### What was supposed to happen?

![image](https://github.com/mehboss/TranspositionRitual/assets/116936416/48fe4b11-155e-491c-847b-9ed21d892c97)

### How do I reproduce this issue?

```bash
1. Teleport to another ritual
```

### Server Version

Current: git-Purpur-1985 (MC: 1.19.4)* * You are running the latest version

### Plugin Version

1.4-BETA

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of TP Rituals and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello, thank you for your patience while I was MIA. Please download the newest update [here](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-teleportation-rituals-1-8-x-1-20-x-creation-limit-networking-system-%E2%97%84%E2%97%84.110584/update?update=564059), and your issue will be resolved.
